name: Frontend CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SaasFrontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=https://api.organizarte.es \
            -t ghcr.io/claubersonpacheco/saas-frontend:latest .

          docker push ghcr.io/claubersonpacheco/saas-frontend:latest

      - name: Verificar Secrets
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST != '' }}"
          echo "SSH_USER: ${{ secrets.SSH_USER != '' }}"
          echo "SSH_KEY : ${{ secrets.SSH_KEY != '' }}"
          echo "SSH_PORT: ${{ secrets.SSH_PORT != '' }}"
          echo "DEPLOY_PATH: ${{ secrets.DEPLOY_PATH != '' }}"
          echo "FRONTEND_SERVICE: ${{ secrets.FRONTEND_SERVICE != '' }}"

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "===== DEBUG ====="
            echo "Usuário:"
            whoami

            echo
            echo "ID:"
            id

            echo
            echo "Grupos:"
            groups

            echo
            echo "Docker Socket:"
            ls -l /var/run/docker.sock || true

            echo
            echo "Docker:"
            sudo docker version || true

            echo
            echo "Docker Compose:"
            sudo docker compose version || true

            echo "================="

            cd "${{ secrets.DEPLOY_PATH }}"

            if [ -n "${{ secrets.GHCR_TOKEN }}" ]; then
              echo "${{ secrets.GHCR_TOKEN }}" | sudo docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            fi

            SERVICE="${{ secrets.FRONTEND_SERVICE }}"
            [ -z "$SERVICE" ] && SERVICE="frontend"

            if sudo docker compose version >/dev/null 2>&1; then
              sudo docker compose pull "$SERVICE"
              sudo docker compose up -d "$SERVICE"
            elif command -v docker-compose >/dev/null 2>&1; then
              sudo docker-compose pull "$SERVICE"
              sudo docker-compose up -d "$SERVICE"
            else
              echo "Docker Compose não encontrado."
              exit 1
            fi

            sudo docker image prune -f